apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: acr27749.azurecr.io/azvote/azure-vote-front
    newTag: 70f80a1d723bea52ed0e9a072176d24e614995aa
  - name: acr27749.azurecr.io/azvote/azure-vote-back
    newTag: 70f80a1d723bea52ed0e9a072176d24e614995aa
resources:
  - manifests.yaml