apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: acr27749.azurecr.io/azvote/azure-vote-front
    newTag: 80f2792815b1118018ed02a1489fc10b847e5915
  - name: acr27749.azurecr.io/azvote/azure-vote-back
    newTag: 80f2792815b1118018ed02a1489fc10b847e5915
resources:
  - manifests.yaml