apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: acr27749.azurecr.io/azvote/azure-vote-front
    newTag: dd6511232cd76b55bdc7ac53a1583cb7e96d5b46
  - name: acr27749.azurecr.io/azvote/azure-vote-back
    newTag: dd6511232cd76b55bdc7ac53a1583cb7e96d5b46
resources:
  - manifests.yaml