apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 

images:
  - name: acr27749.azurecr.io/azvote/azure-vote-front
    newTag: 1ab591832ed7273ed708889972ba3473df7739a2
  - name: acr27749.azurecr.io/azvote/azure-vote-back
    newTag: 1ab591832ed7273ed708889972ba3473df7739a2
resources:
  - manifests.yaml